language: php
sudo: false

php:
    - 7.3

cache:
    directories:
        - $HOME/.composer/cache

addons:
    sonarcloud:
        organization: "jeromegamez-github"

git:
    depth: false

install: composer update --no-interaction --no-suggest --no-progress

script:
    - vendor/bin/phpstan analyze -c phpstan.neon.dist --no-interaction --no-progress
    - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=coverage-report.clover --log-junit=test-report.xml
    - sonar-scanner
