language: php
sudo: false

php:
    - 7.1
    - 7.2
    - 7.3
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

addons:
    sonarcloud:
        organization: "jeromegamez-github"

git:
    depth: false

install: composer update --no-interaction --no-suggest --no-progress

script:
    - vendor/bin/phpstan analyze -c phpstan.neon.dist --no-interaction --no-progress
    - vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover coverage.clover --log-junit tests.xml
    - sonar-scanner
