name: Tests

on:
  pull_request:
  push:

jobs:
  tests:
    name: PHP ${{ matrix.php }}
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php: ["7.3", "7.4", "8.0", "8.1", "8.2", "8.3", "8.4", "8.5"]
        include:
          - php: "8.6"
            composer-options: "--ignore-platform-req=php+"

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - uses: ramsey/composer-install@v4
        with:
          composer-options: ${{ matrix.composer-options }}

      - name: Setup Problem Matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Run PHPUnit
        run: vendor/bin/phpunit --testdox
